apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "qq"
  description: "qq"
  annotations:
    github.com/project-slug: zhul-test/qq
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: experimental
  owner: "qq"
